CREATE TABLE ShareLink (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    hashKey VARCHAR(32) NOT NULL,
    routeUrl VARCHAR(1024) NOT NULL,
    title VARCHAR(128) NOT NULL,
    content VARCHAR(128) NOT NULL,
    imgUrl VARCHAR(512) NOT NULL,
    CONSTRAINT primary_key PRIMARY KEY (id)
);

CREATE INDEX idx_share_hashKey ON ShareLink(hashKey);